pipelines:
  branches:
    dev:
      - step:
          name: Build
          caches:
            - gradle
          script:
            - chmod +x gradlew
            - bash ./gradlew build
            - ls
          artifacts:
            - $TARGET_PATH
      - step:
          deployment: test
          script:
            - pipe: atlassian/sftp-deploy:0.5.8
              variables:
                USER: $SSH_USER
                SERVER: $SERVER
                REMOTE_PATH: $REMOTE_PATH
                LOCAL_PATH: $LOCAL_PATH
    master:
      - step:
          name: Build
          caches:
            - gradle
          script:
            - bash ./gradlew build
          artifacts:
            - $TARGET_PATH
      - step:
          deployment: test
          script:
            - pipe: atlassian/sftp-deploy:0.5.8
              variables:
                USER: $SSH_USER
                SERVER: $SERVER
                REMOTE_PATH: $REMOTE_PATH
                LOCAL_PATH: $LOCAL_PATH