image: atlassian/default-image:2

options:
  docker: true
  size: 2x

pipelines:
  branches:
    dev:
      - step:
          deployment: test
          script:
            - pipe: atlassian/sftp-deploy:0.5.8
              variables:
                USER: $SSH_USER
                SERVER: $SERVER
                REMOTE_PATH: $REMOTE_PATH
                LOCAL_PATH: $LOCAL_PATH
    master:
      - step:
          deployment: test
          script:
            - pipe: atlassian/sftp-deploy:0.5.8
              variables:
                USER: $SSH_USER
                SERVER: $SERVER
                REMOTE_PATH: $REMOTE_PATH
                LOCAL_PATH: $LOCAL_PATH
definitions:
  services:
  docker:
    memory: 4096
